---
 - name: Remove console from Xenodm
   lineinfile:
     path: /etc/X11/xenodm/Xsetup_0
     regexp: '^.*xconsole.*$'
     state: absent
   tags:
     - system-config 
     - remove-console

 - name: Setup doas
   lineinfile:
     path: /etc/doas.conf
     line: permit nopass keepenv :wheel
     create: yes
     state: present
   tags:
     - system-config
     - setup-doas
