---
 - block:
   - name: Download dotfiles
     git:
       repo: 'https://github.com/desnudopenguino/dotfiles.git'
       dest: "/home/{{ user_name }}/dotfiles"
       force: yes
     tags:
       - user-config
       - dotfiles

   - name: Install dotfiles
     shell: make
     args:
       chdir: "/home/{{ user_name }}/dotfiles"
     tags:
       - user-config
       - dotfiles
   
   - name: Download scripts
     git:
       repo: 'https://github.com/desnudopenguino/scripts.git'
       dest: "/home/{{ user_name }}/scripts"
     tags:
       - user-config
       - scripts

   - name: Download WorkLogger
     git:
       repo: 'https://github.com/desnudopenguino/wl.git'
       dest: "/home/{{ user_name }}/wl"
     tags:
       - user-config
       - wl

   - name: Initialize WorkLogger
     shell: make init
     args:
       chdir: "/home/{{ user_name }}/wl"
     tags:
       - user-config
       - wl

   - name: Add .kshrc to .profile
     lineinfile:
       path: "/home/{{ user_name }}/.profile"
       line: ". ~/.kshrc"
       state: present
     tags:
       - user-config
       - source-kshrc

   - name: Create todo.txt
     file:
       path: "/home/{{ user_name }}/todo.txt"
       owner: "{{ user_name }}"
       group: "{{ user_name }}"
       mode: 0644
       state: touch
     tags:
       - user-config
       - create-todo

   become: yes
   become_method: su
   become_user: "{{ user_name }}"

 - name: Install WorkLogger
   shell: make global
   args:
     chdir: "/home/{{ user_name }}/wl"
   tags:
     - user-config
     - wl

 - name: Install WorkLogger Man
   shell: make man
   args:
     chdir: "/home/{{ user_name }}/wl"
   tags:
     - user-config
     - wl
