---
 - name: Copy dhclient.conf
   become: yes
   become_method: doas
   become_user: root
   template:
     src: templates/dhclient.conf.j2
     dest: /etc/dhclient.conf
     owner: root
     group: wheel
     mode: 0644
   notify: restart dns
   tags:
     - dns
     - config-dns
