---
 - name: Remove console from Xenodm
   lineinfile:
     path: /etc/X11/xenodm/Xsetup_0
     regexp: '^.*xconsole.*$'
     line: '    xsetroot -solid "#282A36"'
   tags:
     - xenodm
     - remove-console

 - name: Setup doas
   lineinfile:
     path: /etc/doas.conf
     line: permit nopass keepenv :wheel
     create: yes
     state: present
   tags:
     - xenodm
     - setup-doas

 - name: Config Xenodm login screen
   copy:
     src: ../templates/Xresources
     dest: /etc/X11/xenodm/Xresources
     owner: root
     group: bin
     mode: 0444
   tags:
     - xenodm
     - xenodm-login
